### ISSUE TITLE
Please publish a fresh maven release

### ISSUE THREAD

**Issue by plipp** [OpenAPITools/openapi-diff#111]
Hi,
we use openapi-diff actively in our projects to find breaking API changes and found out that in version 1.2. NullPointerExceptions can happen in case of incompatibilities. Additionally with 1.2 we have to tweak especially the io.swagger.parser.v3 version in our pom to avoid conflicts. Both  is fixed in the master. 

Thus it would be great to have a newly tagged maven release in the mvnrepository with all the library updates and fixes since 1.2.

**Comment by mspiegel31** [comment]
any progress on this?  We are running into a similar issue as well.

**Comment by thiagoarrais** [comment]
I'm not sure this repo is active any longer. Has anyone contacted @quen2404 on transferring ownership?

**Comment by thiagoarrais** [comment]
By the way, this is the best openapi differ around. And I don't say this lightly as I have evaluated some differs from some big players.

**Comment by plipp** [comment]
I tried to contact @quen2404 <https://github.com/quen2404> directly by mail
- unfortunately no response.
I really would like to take over and now consider to continue on a fork...

Am Mi., 11. Dez. 2019 um 13:57 Uhr schrieb Thiago Arrais <
notifications@github.com>:

**Comment by quen2404** [comment]
Sorry everyone! I'm a little busy these days.
I saw your mail @plipp, sorry for the delay !

**Comment by quen2404** [comment]
This project is not dead, i'm still using it. I will take time to merge the current pull requests

**Comment by plipp** [comment]
BTW: I completly agree with @thiagoarrais :
This is also the best openapi-diff implementation, I could find, and I like its clear coding style much.
Therefore I'm really happy, that it is not discontinued.

**Comment by thiagoarrais** [comment]
It is great hearing back from you @quen2404!

**Comment by mspiegel31** [comment]
@quen2404 any plans on doing this?  I still only see 1.2.0 [in maven central](https://search.maven.org/search?q=g:com.qdesrame).

don't mean to be a nag;  we really like this tool but would like to benefit from some of the changes/fixes in 2.x!

**Comment by quen2404** [comment]
Hi guys, today i'm currently working in this project.
I merged some pull requests, but i want to merge the #94 before release 2.0.0 because it's a realy big breaking change and i don't want to have to release a 3.0.0 soon after the 2.0.0.
I hope you understand that.

**Comment by joschi** [comment]
See https://search.maven.org/search?q=g:com.github.joschi.openapi-diff for an up-to-date release (of a fork of this project).

You can find a self-contained JAR of openapi-diff at https://repo1.maven.org/maven2/com/github/joschi/openapi-diff/cli/2.0.0-beta.1/cli-2.0.0-beta.1-jar-with-dependencies.jar.
```
# curl -o openapi-diff.jar 'https://repo1.maven.org/maven2/com/github/joschi/openapi-diff/cli/2.0.0-beta.1/cli-2.0.0-beta.1-jar-with-dependencies.jar'
# java -jar openapi-diff.jar -h
usage: openapi-diff <old> <new>
    --debug                     Print debugging information
    --error                     Print error information
    --fail-on-changed           Fail if API changed but is backward
                                compatible
    --fail-on-incompatible      Fail only if API changes broke backward
                                compatibility
 -h,--help                      print this message
    --header <property=value>   use given header for authorisation
    --html <file>               export diff as html in given file
    --info                      Print additional information
 -l,--log <level>               use given level for log (TRACE, DEBUG,
                                INFO, WARN, ERROR, OFF). Default: ERROR
    --markdown <file>           export diff as markdown in given file
    --off                       No information printed
    --query <property=value>    use query param for authorisation
    --state                     Only output diff state: no_changes,
                                incompatible, compatible
    --text <file>               export diff as text in given file
    --trace                     be extra verbose
    --version                   print the version information and exit
    --warn                      Print warning information
```

**Comment by jmini** [comment]
Will be solved with:
https://github.com/OpenAPITools/openapi-diff/issues/165

I am closing this for now.
