### ISSUE TITLE
Please update the available Docker image in DockerHub to the latest state

### ISSUE THREAD

**Issue by binaryunary** [OpenAPITools/openapi-diff#130]
Hi, and thank you for creating this tool. Would it be possible to update the publicly available Docker image and perhaps include this process into the CI pipeline?

**Comment by joschi** [comment]
See https://hub.docker.com/r/joschi/openapi-diff/ for an up-to-date Docker image of openapi-diff (forked from this project).

**Comment by jmini** [comment]
Now that the project is moving to the `OpenAPITools` org, this will be solved with https://github.com/OpenAPITools/openapi-diff/issues/165.

I am closing this for now.
