### ISSUE TITLE
Invalid backward compatibility result for new read-only property in PUT operations

### ISSUE THREAD

**Issue by trohrberg** [OpenAPITools/openapi-diff#136]
Hi, thank you for creating this tool which helps us a lot in our project. We noticed the following deviation between the tool's responses concerning backward compatibility and our expectation. I would like to discuss that here to see if you agree with our perspective:

We consider the addition of a new read-only property into an API model as a breaking change for PUT operations. A client not knowing of the new read-only property would get a resource from the API which includes the new read-only property and would send a full update back via PUT omitting that new property. The result is that the property would be cleared on the server side as the client did not sent the retrieved value back.

I will shortly provide a pull request fixing this issue (if it is one) and appreciate a lot your comments and opinions on whether this is an issue or not.

**Comment by joschi** [comment]
@trohrberg Thanks for reporting this!

Would it be possible for you to open a pull request in this repository based on https://github.com/trohrberg/openapi-diff/commit/25bd1544c70832a68a3f80da28b92c7ad285d886?

**Comment by trohrberg** [comment]
Hello joschi,

I already provided a pull rqeuest for this issue (https://github.com/OpenAPITools/openapi-diff/pull/137) and that PR has already been merged. However, I did not check the latest version yet and if the problem is completely solved now. I will do that soon, but you may close this issue anyways.

Best regards
Timo

**Comment by joschi** [comment]
Resolved in #137.
