### ISSUE TITLE
Activity of this project – Fork

### ISSUE THREAD

**Issue by joschi** [OpenAPITools/openapi-diff#157]
Hi everyone,

it currently looks like the development activity in this project has stalled. The last commit was on January 8, 2020 (443246ff8c521a8091f5a7f6f6b452303198958a) and issues and PRs don't seem to be addressed.

I've tried to contact @quen2404 via email but unfortunately didn't receive a response.

So I've forked this project, applied many of the open PRs and added some other bugfixes, and published the new version(s) to Maven Central and Docker Hub:

* Git repository: https://github.com/joschi/openapi-diff
* Docker: https://hub.docker.com/r/joschi/openapi-diff
* Maven: https://search.maven.org/search?q=g:com.github.joschi.openapi-diff

Since I don't just want to start yet another fork of this project with limited lifetime, I've contacted the fine people at https://github.com/OpenAPITools/ to discuss whether `openapi-diff` could live in their GitHub organization.

@elibracha I've seen that you've also been working on a fork (https://github.com/elibracha/openapi-diff) and an extension (https://github.com/elibracha/openapi-diff-ignore) to this project. Would you be interested in joining forces?

**Comment by quen2404** [comment]
Hi Joshi,
Thank you for your investment in this project. As you can see, i'm not very active on this project.
I'm currently working with openapi-tools organization to integrate this repository. So soon, it should be more active.
Sorry, i didn't read your email, which address did you use ?
If you want, i can add you as a contributor to this project

**Comment by joschi** [comment]
Hi Quentin, thank you so much for your response!

>  Sorry, i didn't read your email, which address did you use ?

I've been using the email address listed in your GitHub profile: quen2404@gmail.com
The mail was sent on May 22, in case you want to check the Inbox or the Spam folder. 😉

With @OpenAPITools getting involved, how should we move on with this repository?
In https://github.com/joschi/openapi-diff, I've merged quite a few of the open pull requests of this repository and fixed some bugs.

What would be your preferred way to continue?

**Comment by joschi** [comment]
@quen2404 Thanks for moving the repository to @OpenAPITools and merging my changes!

I'm going to close this ticket since the open issues have been addressed.

I've created #165 as a follow-up issue to address moving the openapi-diff artifacts to the organization.

**Comment by jmini** [comment]
I have create a Slack channel for `openapi-diff` in the OpenAPITools Slack:
https://openapi-generator.slack.com/archives/C01A5503T2M

I will update the README of this repo later today.
