### ISSUE TITLE
Getting a runtime error while trying to compare two yaml file

### ISSUE THREAD

**Issue by Sourabh25** [OpenAPITools/openapi-diff#182]
getting the below error:

```
Exception in thread "main" java.lang.RuntimeException: Cannot read old OpenAPI spec
	at com.qdesrame.openapi.diff.core.OpenApiCompare.notNull(OpenApiCompare.java:106)
	at com.qdesrame.openapi.diff.core.OpenApiCompare.fromSpecifications(OpenApiCompare.java:101)
	at com.qdesrame.openapi.diff.core.OpenApiCompare.fromLocations(OpenApiCompare.java:90)
	at com.qdesrame.openapi.diff.core.OpenApiCompare.fromLocations(OpenApiCompare.java:77)
	at com.comcast.ymldiff.App.main(App.java:18)
```

both are valid yaml file.

**Comment by jimschubert** [comment]
@Sourabh25 can you provide minimal reproducible specs for new and old specs, as well as how you're invoking?

**Comment by Sourabh25** [comment]
@jimschubert I was not able to attach the .yaml files as this type is not supported to be uploaded.
here is the content of the file

 spring: 
  application: 
    name: xyz
  cloud: 
    config: 
      enabled: true
      failFast: true
      label: master
      uri: "http://configserver001.dt-u2.cf.abc.net"
  profiles: 
    active: dev


Please find below the code

`public class App {

    public static final String OPENAPI_DOC1 = "bootstrap.yaml";
    public static final String OPENAPI_DOC2 = "bootstrap1.yaml";


    public static void main(String[] args) {
        ChangedOpenApi changedOpenApi = OpenApiCompare.fromLocations(OPENAPI_DOC1, OPENAPI_DOC2);

    }

}`

Kindly let me know if you need any more information.

**Comment by jimschubert** [comment]
@Sourabh25 this project compares [OpenAPI Specification](https://spec.openapis.org/oas/v3.0.3.html) documents. What you've provided is a spring yaml configuration. I'd recommend finding your OpenAPI document(s) and try again, and this should solve your issue.

**Comment by Sourabh25** [comment]
okay with open api spec yaml file this is working.

**Comment by Swap3093** [comment]
I also Facing same issue can not read old/new  open API  spe in Restest JAVA ......any solution

**Comment by joschi** [comment]
@Swap3093 Please open a new topic in the [Discussions](https://github.com/OpenAPITools/openapi-diff/discussions) of this project and provide as much information as possible, such as the exact version of openapi-diff you're using and the OpenAPI specs which cause the issue.
