### ISSUE TITLE
Docker image for beta11 missing

### ISSUE THREAD

**Issue by languitar** [OpenAPITools/openapi-diff#269]
There's no tag for the beta 11 release on dockerhub.

**Comment by joschi** [comment]
OpenAPI Diff 2.0.0-beta.11 is now also available on Docker Hub:
https://hub.docker.com/layers/openapitools/openapi-diff/2.0.0-beta.11/images/sha256-12872658224211719c977bb8fda0fd3550472360ee088be6a7f03d1bdffc484c?context=explore
