### ISSUE TITLE
Using maven plugin prevents building from tarball

### ISSUE THREAD

**Issue by dvzrv** [OpenAPITools/openapi-diff#299]
Hi! When packaging 2.0.0 for Arch Linux I realized that the tool can not be built from a tarball of a release as long as there is the git hooks maven plugin in use:

https://github.com/OpenAPITools/openapi-diff/blob/ed6345ee792f86ba20397356bc08066ac53373b2/pom.xml#L290-L294

https://github.com/OpenAPITools/openapi-diff/blob/ed6345ee792f86ba20397356bc08066ac53373b2/pom.xml#L349-L366

As this seems to be only for code formatting, is it possible to circumvent its use (aside from removal), when using `mvn clean install`?

**Comment by joschi** [comment]
You can disable the `githook-maven-plugin` by setting the system property `githook.plugin.skip` to `false`.

https://github.com/phillipuniverse/githook-maven-plugin#additional-configuration-options

**Comment by joschi** [comment]
@dvzrv Why would you build the project from scratch when you could download the official JAR from Maven Central? It's not like your byte code would be any different.

- https://search.maven.org/artifact/org.openapitools.openapidiff/openapi-diff-cli/2.0.0/jar
- https://repo1.maven.org/maven2/org/openapitools/openapidiff/openapi-diff-cli/2.0.0/

**Comment by dvzrv** [comment]
> You can disable the githook-maven-plugin by setting the system property githook.plugin.skip to false.

Thanks, I will look into that! :)

> Why would you build the project from scratch when you could download the official JAR from Maven Central?

We generally build everything (that we can) from source. This allows for reproducibility and not being affected by supply chain attacks on a binary repository such as maven central or a compromised build infrastructure in which the official jar is being built.
Furthermore Arch Linux invests into having [reproducible builds](https://reproducible-builds.org/) for all of its packages.

> It's not like your byte code would be any different.

In fact, it would be, because maven builds are usually not bit-by-bit reproducible, [unless configured so](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) (for this purpose [strip-nondeterminism](https://salsa.debian.org/reproducible-builds/strip-nondeterminism) is currently used to strip the resulting jar from nondeterministic strings such as timestamps).

**Comment by joschi** [comment]
> In fact, it would be, because maven builds are usually not bit-by-bit reproducible

Yeah, I've heard that one before. 😉
https://github.com/dropwizard/dropwizard/commit/c9158ff430c77fd0eb30f61f5a6b5ca185ed69e5

**Comment by joschi** [comment]
@dvzrv This issue should've been resolved via #300 and #301.

**Comment by dvzrv** [comment]
@joschi many thanks! :heart:
