### ISSUE TITLE
ENUM changes

### ISSUE THREAD

**Issue by jackbilestech** [OpenAPITools/openapi-diff#303]
### Discussed in https://github.com/OpenAPITools/openapi-diff/discussions/292

<div type='discussions-op-text'>

<sup>Originally posted by **Roman-Bober** November 25, 2021</sup>
Hi,
I wonder why enum changes gives "brocken backward compatability"
Shouldn't be if enum is added **at the end of enum list** it should be **backward compatible**?

Thank you,
Roman</div>

I too am seeing the above issue whe appending an item to a string enum.

**Comment by cTAbdIsi** [comment]
@jackbilestech Changes to enums are not breaking in every programming language or in Java it is breaking and causes runtime errors. That is why Zalando works with `x-extensible-enum` https://opensource.zalando.com/restful-api-guidelines/#112.

There are numerous solutions on the market, but no official ones in the OpenAPI standard.

**Comment by joschi** [comment]
See also: https://github.com/OpenAPITools/openapi-diff/discussions/292#discussioncomment-2265299

While it's up to the specific implementation of clients how to act on the change, adding a previously invalid value to an existing enum is a breaking change in my opinion.

**Comment by doshidhaval** [comment]
We might be able to reach a decision here, but can we add a parameter to the CLI to allow us to treat ENUM as a breaking change or not. Something similar to https://openapi-generator.tech/docs/generators/java `enumUnknownDefaultCase` parameter does

**Comment by mcwhitak** [comment]
To echo what @doshidhaval said, an enum addition can be considered a compatible change if a `default` case exists (say: `UNKNOWN`) but otherwise is breaking.

This gets thornier when considering evolution over time (imagine changing a default enum value to something that previously didn't exist) however.
