### ISSUE TITLE
Changes in 'minLength' are not detected (wheras 'maxLength' is detected)

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#481]
Adding or changing or removing 'minLength' is not detected a a change.

**V1**
```
schema:
   type: string
```
**V2 (added 'minLength'):
```
schema:
   type: string
   minLength: 1
```

Same with changing/removing the field.

**Comment by joschi** [comment]
Duplicate of https://github.com/OpenAPITools/openapi-diff/issues/461
