### ISSUE TITLE
Treat new PUT request properties as compatible

### ISSUE THREAD

**Issue by westse** [OpenAPITools/openapi-diff#537]
Currently new PUT request properties are treated as incompatible. This is due to #136 (with PR #137) which appear invalid in intent, implementation, and test.
- Invalid in intent: #136 claims that adding a readOnly property to the request body of a PUT request is a breaking change because clients will begin to omit it and the server will interpret the omission as a directive to delete the property. This is incorrect because the server should expect, [per the OAS spec](https://spec.openapis.org/oas/v3.0.3#fixed-fields-19), that readOnly properties "SHOULD NOT be sent as part of the request". So it would be a bug for the server to delete any data associated with the readOnly property. Regardless, the API is left unbroken if the server simply ignores readOnly properties.
- Invalid in implementation: the code treats as incompatible any new PUT request property, not just readOnly properties.
- Invalid in test: no readOnly properties are tested.

In theory one could argue that some servers might enforce the "SHOULD NOT" language of the spec by returning validation errors where they didn't before, and this would constitute an API breakage. But that should be discussed in a different issue.

**Comment by mas-chen** [comment]
+1, or at least have this configurable

**Comment by mas-chen** [comment]
Linking your fix here: https://github.com/OpenAPITools/openapi-diff/pull/538

**Comment by mas-chen** [comment]
@joschi do you think you could help get this fix in? Or there another workaround?

**Comment by westse** [comment]
@mas-chen Agreed on the configurability. On this note, I'm working on a PR to enable/disable via configuration *each* individual backward incompatible checks. (It builds on #546 which exhaustively tests each check). Stay tuned.

**Comment by mas-chen** [comment]
Thank you @westse @joschi!

**Comment by mas-chen** [comment]
@joschi will we have a beta release soon? I'm eager to test this out!

**Comment by joschi** [comment]
> @joschi will we have a beta release soon? I'm eager to test this out!

See https://github.com/OpenAPITools/openapi-diff/releases/tag/2.1.0-beta.7. Maven Central should be synced in a few minutes to hours.
