### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by jsoref** [OpenAPITools/openapi-diff#624]
https://github.com/OpenAPITools/openapi-diff/blob/057e9caeb55794de22bd14c43a62799637ab5718/README.md?plain=1#L10

Leads to:
> Slack
> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by joschi** [comment]
@jsoref Thanks for reporting this! I've updated the link in the README file.
