### ISSUE TITLE
Should openapi-diff-core.jar be including logback.xml?

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [OpenAPITools/openapi-diff#638]
Not sure if this is a bug or something we're doing wrong. But after upgrading to spring boot 3 our application no longer uses our `logback-spring.xml`. Stepping through the spring boot code that initializes logging I see that it's finding a `logback.xml` and the only one I found in the classpath resources is from `openapi-diff-core.jar`. 

If I change our `build.gradle` from:

```
implementation "org.openapitools.openapidiff:openapi-diff-core:2.1.0-beta.8"
```

to:

```
compileOnly "org.openapitools.openapidiff:openapi-diff-core:2.1.0-beta.8"
```

Our `logback-spring.xml` is picked up and used. Of course, our app no longer runs :-(

So, should the jar file include `logback.xml`? Or are we doing something wrong?

**Comment by joschi** [comment]
@Blackbaud-JasonBodnar Thanks for reporting this! You're absolutely correct and the Logback configuration shouldn't have been a part of the `openapi-diff-core` artifact.

**Comment by Blackbaud-JasonBodnar** [comment]
Thanks!
