### ISSUE TITLE
Error resolving schema and Reason: ref does not exist

### ISSUE THREAD

**Issue by akhilarao29** [OpenAPITools/openapi-diff#707]
Hello,
I am experimenting with openapi-diff and also an open api spec of SysML. Here is the link where you can find the spec: http://sysml2.intercax.com:9000/docs/, I have downloaded the same and named it as openspec1.json. Made a copy of it, made some changes and renamed it as openspec2.json.
When i try to find the difference using the command:  docker run --rm -t -v $(pwd):/specs:ro -w /specs openapitools/openapi-diff:latest  openspec1.json openspec2.json  i get the following error "Error resolving schema #/components/schemas/Project"
I have tried with the previous versions as well and received the same error.
Attaching openspec1.json, openspec2.json and also the error log:
[openapi-deff-errorlog.txt](https://github.com/user-attachments/files/16885406/openapi-deff-errorlog.txt)
[openspec1.json](https://github.com/user-attachments/files/16885407/openspec1.json)
[openspec2.json](https://github.com/user-attachments/files/16885408/openspec2.json)

**Comment by joschi** [comment]
The problem is that the referenced schema `Project` (and all the others) don't exist in the OpenAPI specification:
```
❯ jq .components.schemas openspec1.json
{}
```

In other words, the OpenAPI specification is invalid or at least incomplete.

**Comment by akhilarao29** [comment]
Hi, 
I am using a valid json now, getting a different error as ERROR io.swagger.v3.parser.util.RemoteUrl - unable to read
java.net.UnknownHostException: www.omg.org but when i do a curl, it gives me a 200
Attaching the file:
[openapi1.json](https://github.com/user-attachments/files/16943948/openapi1.json)
