### ISSUE TITLE
openapi-diff library includes a logging implementation

### ISSUE THREAD

**Issue by gmcelhoe** [OpenAPITools/openapi-diff#93]
It would allow easier reuse if the command-line main was in a different JAR then the library that does the differencing.

There have not been any commits recently, is this project still under development?

**Comment by quen2404** [comment]
Hi @gmcelhoe,
sorry for the late, it was my holidays.
Yes this project is still under development but i don't have a lot of time to dedicate to it...

About splitting cli main & library, yes it could be a good idea.

**Comment by gmcelhoe** [comment]
Hope you had a good time!  Good to hear about the project, I will create a pull request and we can discuss it further.

Glenn

**Comment by gmcelhoe** [comment]
#94 seems like a logical first step for dividing the cli and library concerns.

**Comment by joschi** [comment]
See https://search.maven.org/search?q=g:com.github.joschi.openapi-diff for a release of split artifacts (core functionality and CLI) of a fork of this project.

**Comment by joschi** [comment]
Fixed in 9ec02909a68b80f104c7ba5b8c29311e77da8684.
